# Generated by Django 3.2 on 2023-09-11 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=True, null=True)),
                ('request_email', models.TextField(blank=True, null=True)),
                ('request_subject', models.TextField(blank=True, null=True)),
                ('request_message', models.TextField(blank=True, null=True)),
                ('approval_email', models.TextField(blank=True, null=True)),
                ('approval_subject', models.TextField(blank=True, null=True)),
                ('approval_message', models.TextField(blank=True, null=True)),
                ('remainder_email', models.TextField(blank=True, null=True)),
                ('remainder_subject', models.TextField(blank=True, null=True)),
                ('remainder_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
            },
        ),
    ]
